### ISSUE TITLE
Chapter view broken?

### ISSUE THREAD

**Issue by aka-raj** [bumpaneer/kodi.repo.bumpaneer#1]
Hello, I REALLY like this skin, one of the best. The chapters view doesn't look good though, at least on Xbian 15.2 RC, there are no thumbnail previews as provided in default Confluence, and the chapter titles are arranged vertically with large amount of white space between. Known issue?

**Comment by bumpaneer** [comment]
It appears this issue is for skin.unity, not for the repo itself.  If so, it should be raised at: https://github.com/bumpaneer/skin.unity/issues .

**Comment by aka-raj** [comment]
Sorry, I didn't realise the distinction. I've raised it again on 
skin.unity. Should I close the original on kodi.repo.bumpaneer?

On 23/10/2015 18:30, bumpaneer wrote:

> It appears this issue is for skin.unity, not for the repo itself. If 
> so, it should be raised at: 
> https://github.com/bumpaneer/skin.unity/issues .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bumpaneer/kodi.repo.bumpaneer/issues/1#issuecomment-150640454.

## 

Richard Jones

**Comment by aka-raj** [comment]
Yes it looks fine on your setup. Not on mine though. I'm on holiday this week but will try to get a screen-shot to you as soon as I can.
